### ISSUE TITLE
Intro does not work

### ISSUE THREAD

**Issue by shawndwells** [pburkholder/freedonia-compliance#13]
Attempting to play with the code. Clone the project locally, and run the `compliance-masonry get` command, receive following error:

```
$ compliance-masonry get
open : no such file or directory
```

How do I begin to troubleshoot this?

**Comment by afeld** [comment]
Hmmmm, that's strange...we should definitely have some a better/more complete error, at the very least. You ran `compliance-masonry get` from the `freedonia-compliance/` directory, yeah? What operating system are you using?

**Comment by shawndwells** [comment]
Using GVM v1.0.22, Compliance Masonry v1.1.2 on OSX 10.11.6 (El Capitan). Did a git clone of the repo, cd'd into it, then ran:

```
$ pwd
/Users/shawnwells/Downloads/freedonia-compliance
$ compliance-masonry get
open : no such file or directory
```

**Comment by shawndwells** [comment]
Also, using Go 1.6

**Comment by jtconnor** [comment]
FYI, I'm working through the tutorial and ran into the same error.

**Comment by jtconnor** [comment]
I poked around a bit in compliance-masonry and it looks like the error comes from:

```
    err = resources.GetResources("", destination, configSchema, getter)
```

in commands/get/get.go

I tried looking at the GetResources implementation and don't understand what's going on there.  For example, GetResources calls getAllRemoteResources which calls getter.GetRemoteResources which then recurses to GetResources 😕

**Comment by gregelin** [comment]
@jtconnor What platform are you on?

**Comment by jtconnor** [comment]
@gregelin 

mac osx 10.11.6

```
$ compliance-masonry -v
Compliance Masonry version 1.1.2
$ go version
go version go1.7.1 darwin/amd64
```

**Comment by gregelin** [comment]
Working for me on Mac OSX 10.10.5.

```
Gregs-MacBook-Pro:exports greg$ compliance-masonry -v
Compliance Masonry version 1.1.1
Gregs-MacBook-Pro:exports greg$ go version
go version go1.6.2 darwin/amd64
```

Here's what my OSX 10.10.5 command line output looks like:

```
$ git clone git@github.com:opencontrol/freedonia-compliance.git freedonia-compliance-issue13
Cloning into 'freedonia-compliance-issue13'...
remote: Counting objects: 237, done.
remote: Total 237 (delta 0), reused 0 (delta 0), pack-reused 237
Receiving objects: 100% (237/237), 1.25 MiB | 0 bytes/s, done.
Resolving deltas: 100% (115/115), done.
Checking connectivity... done.
$ cd freedonia-compliance-issue13/
$ tree
.
├── AU_policy
│   └── component.yaml
├── LICENSE
├── Makefile
├── README.md
├── assets
│   ├── detailpage.png
│   ├── example.pdf
│   ├── frontpage.png
│   └── pdffirstpage.png
├── markdowns
│   ├── README.md
│   ├── SUMMARY.md
│   └── docs
│       ├── Waterfall_model.png
│       └── about-the-ssp.md
└── opencontrol.yaml

4 directories, 13 files

$ compliance-masonry -v
Compliance Masonry version 1.1.1

$ compliance-masonry get
Already exists
$ tree
.
├── AU_policy
│   └── component.yaml
├── LICENSE
├── Makefile
├── README.md
├── assets
│   ├── detailpage.png
│   ├── example.pdf
│   ├── frontpage.png
│   └── pdffirstpage.png
├── markdowns
│   ├── README.md
│   ├── SUMMARY.md
│   └── docs
│       ├── Waterfall_model.png
│       └── about-the-ssp.md
├── opencontrol.yaml
└── opencontrols
    ├── certifications
    │   └── FredRAMP-low.yaml
    ├── components
    │   └── AU_policy
    │       └── component.yaml
    └── standards
        └── FRIST-800-53.yaml

9 directories, 16 files

$ compliance-masonry docs gitbook FredRAMP-low
New Gitbook Documentation Created

$ cd exports && gitbook pdf ./ ./compliance.pdf
info: 6 plugins are installed 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 11 pages 
info: found 1 asset files 
info: >> generation finished with success in 7.1s ! 
info: >> 1 file(s) generated 
Gregs-MacBook-Pro:exports greg$ open compliance.pdf 

```

**Comment by gregelin** [comment]
But as I stated, I'm having problems getting compliance-masonry to install on Ubuntu 15.10.

```
root@kbs:/tmp# go version
The program 'go' can be found in the following packages:
 * gccgo-5
 * golang-go
Try: apt-get install <selected package>
root@kbs:/tmp# compliance-masonry
compliance-masonry: command not found

root@kbs:/tmp# apt-get install golang-go
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  golang-race-detector-runtime golang-src
Suggested packages:
  bzr golang-go.tools mercurial subversion
The following NEW packages will be installed:
  golang-go golang-race-detector-runtime golang-src
0 upgraded, 3 newly installed, 0 to remove and 72 not upgraded.
Need to get 30.7 MB of archives.
After this operation, 213 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirrors.digitalocean.com/ubuntu/ wily-updates/main golang-src amd64 2:1.5.1-0ubuntu2.1 [6,132 kB]
.
.
.
Setting up golang-go (2:1.5.1-0ubuntu2.1) ...
update-alternatives: using /usr/lib/go/bin/go to provide /usr/bin/go (go) in auto mode
Setting up golang-race-detector-runtime (0.0+svn229396-0ubuntu1) ...

root@kbs:/tmp# go version
go version go1.5.1 linux/amd64


root@kbs:/tmp# go get github.com/opencontrol/compliance-masonry
package github.com/opencontrol/compliance-masonry: cannot download, $GOPATH not set. For more details see: go help gopath

root@kbs:/tmp# GOPATH=$HOME/go
root@kbs:/tmp# export GOPATH

root@kbs:/tmp# go get github.com/opencontrol/compliance-masonry
root@kbs:/tmp# compliance-masonry
compliance-masonry: command not found
```

**Comment by gregelin** [comment]
@jtconnor @shawndwells What is the absolute directory path to your respective `freedonia-compliance` repository?
And can you share the directory permissions for `freedonia-compliance` directory and files inside?

I am wondering if we are dealing with subtle file path and file permission issue that might exist between OSX 10.10 and OSX 10.11.

**Comment by shawndwells** [comment]
Retracing Gregs steps....

On 10/19/16 4:12 PM, Greg Elin wrote:

> |Gregs-MacBook-Pro:tmp greg$ git clone
> git@github.com:opencontrol/freedonia-compliance.git
> freedonia-compliance-issue13 Cloning into
> 'freedonia-compliance-issue13'...|
> $ cd /tmp

$ git clone git@github.com:opencontrol/freedonia-compliance.git
Cloning into 'freedonia-compliance'...
remote: Counting objects: 237, done.
remote: Total 237 (delta 0), reused 0 (delta 0), pack-reused 237
Receiving objects: 100% (237/237), 1.25 MiB | 0 bytes/s, done.
Resolving deltas: 100% (115/115), done.
Checking connectivity... done.

||

> |Gregs-MacBook-Pro:tmp greg$ cd freedonia-compliance-issue13/
> Gregs-MacBook-Pro:freedonia-compliance-issue13 greg$ tree |
> $ cd freedonia-compliance/
> sdw:freedonia-compliance shawnwells$ tree
> .
> ├── AU_policy
> │   └── component.yaml
> ├── LICENSE
> ├── Makefile
> ├── README.md
> ├── assets
> │   ├── detailpage.png
> │   ├── example.pdf
> │   ├── frontpage.png
> │   └── pdffirstpage.png
> ├── markdowns
> │   ├── README.md
> │   ├── SUMMARY.md
> │   └── docs
> │       ├── Waterfall_model.png
> │       └── about-the-ssp.md
> └── opencontrol.yaml

4 directories, 13 files

(matches greg)

> |Gregs-MacBook-Pro:freedonia-compliance-issue13 greg$ go version go
> version go1.6.2 darwin/amd64
> Gregs-MacBook-Pro:freedonia-compliance-issue13 greg$ compliance-masonry |

$ go version
go version go1.6 darwin/amd64
sdw:freedonia-compliance shawnwells$ compliance-masonry
NAME:
   Compliance Masonry - Open Control CLI Tool

USAGE:
   compliance-masonry [global options] command [command options]
[arguments...]

VERSION:
   1.1.2

_ISSUE_: Greg on compliance-masonry v1.1.1, whereas latest is 1.1.2.

> |Gregs-MacBook-Pro:freedonia-compliance-issue13 greg$
> compliance-masonry get Already exists|
> $ compliance-masonry get
> open : no such file or directory

*ISSUE: *Greg output as "already exists," whereas I receive no such file.

Perhaps all due to differing version of compliance-masonry?

**Comment by afeld** [comment]
Arrrgh, just reproduced on my machine using https://github.com/opencontrol/compliance-masonry/tree/e82c819821cbc60d19564f55de4f48e4c067ff65. I just tried [the _actual_ `v1.1.2` release](https://github.com/opencontrol/compliance-masonry/releases/tag/v1.1.2) and it worked on `freedonia-compliance/` (😅) @shawndwells @jtconnor Try this:
1. Remove the existing version
   
   ``` shell
   rm `which compliance-masonry`
   ```
2. Reinstall using the new instructions at https://github.com/opencontrol/compliance-masonry#installation

Assuming you have the same experience, this means there was some bug introduced in https://github.com/opencontrol/compliance-masonry/compare/v1.1.2...e82c819821cbc60d19564f55de4f48e4c067ff65, which is not a _huge_ surprise given how drastic the changes were. /cc @jcscottiii 

@gregelin It looks like your issue [above](https://github.com/opencontrol/freedonia-compliance/issues/13#issuecomment-254927480) is a `GOPATH` and/or `PATH` problem...mind if we take that to Slack?

**Comment by afeld** [comment]
Also, moving discussion of the actual bug to https://github.com/opencontrol/compliance-masonry/issues/234.

**Comment by jtconnor** [comment]
I just confirmed that installing compliance-masonry from the v1.1.2 tag fixes the `compliance-masonry get` error:

```
# cd to compliance-masonry repo
$ git checkout v1.1.2
$ go install
...
# cd to freedonia-compliance repo
$ compliance-masonry get
Compliance Dependencies Installed
```

Thanks for your responsiveness and help looking into the issue @gregelin @afeld @shawndwells
