### ISSUE TITLE
Freedonia-aws-compliance not being fetched

### ISSUE THREAD

**Issue by tankcdr** [pburkholder/freedonia-compliance#17]
I have followed instructions fairly closely and can build a gitbook and pdf. However, the 'systems' element in the opencontrol.yaml is not being fetched. Using compliance-masonry appears to work fine, but the AWS package is not being downloaded.

```
systems:
   - url: https://github.com/opencontrol/freedonia-aws-compliance/
      revision: master
```

As such, much of the generated documentation has, "No information found for the combination of standard FRIST-800-53 and control PE-2" as a result. 

Is there a change to the yaml format? is this a defect with compliance masonry?

**Comment by gregelin** [comment]
@tankcdr Not 100% sure of the issue. Have removed dependency from this simple example in commit 069ed99 and also made sure Freedonia works with hyperGRC, a GUI for viewing OpenControl.
